### ISSUE TITLE
Overflown (text) column content should be somehow visual

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-grid#1304]
The default theme (Lumo) don't show any indication of column borders which may make it very hard for reader to know they see the whole content of the column. Overflown text could be clipped with ellipsisis or with some other visual indication that not all is shown. 

Below an example screenshot (Ingmar is actually Ingman):

<img width="166" alt="screen shot 2018-05-22 at 15 08 54" src="https://user-images.githubusercontent.com/1478052/40361665-c6cff004-5dd2-11e8-85bf-3ffb960f1be3.png">

**Comment by mstahv** [comment]
@jouni, any ideas?

**Comment by jouni** [comment]
Here’s a workaround:

```html
<dom-module id="grid-cell-overflow-fix" theme-for="vaadin-grid">
  <template>
    <style>
      [part~="cell"] ::slotted(vaadin-grid-cell-content) {
        text-overflow: ellipsis;
      }
    </style>
  </template>
</dom-module>
```

Be aware, though, that this can cause the selection column checkboxes and other content like buttons, which you would not expect to truncate, to also be truncated with an ellipsis (at least in Firefox).

I seem to have forgotten why I opted to not adding truncation in other browsers. But I do remember that I would have liked to add it as a default, but some things ended up not working as expected.

**Comment by jouni** [comment]
Actually, it was in Chrome where strange things happen:

<img width="110" alt="screen shot 2018-05-22 at 15 40 10" src="https://user-images.githubusercontent.com/66382/40362868-78f1f568-5dd6-11e8-8234-8ccb02801b75.png">

**Comment by jouni** [comment]
Can’t seem to reproduce any other problems at the moment. If we can find a way to avoid the selection column checkboxes from showing the ellipsis, I would add the text-overflow property to the core styles.

**Comment by tomivirkki** [comment]
Fixed by https://github.com/vaadin/vaadin-grid/pull/1446

**Comment by christophe-g** [comment]
@tomivirkkim, @jouni  - i still experience the same issue for material theme (chrome):

First render is fine, but checkin/unchecking causes:  
![image](https://user-images.githubusercontent.com/1168053/50241676-7010c300-03c8-11e9-812a-5d29c8d8f07f.png)
