### ISSUE TITLE
Having additional header rows on initial paint disables resizing

### ISSUE THREAD

**Issue by Wnt** [vaadin/vaadin-grid#1577]
Resize handle is not visible / usable in the Grid if there is a extra header rows in the grid.
Interestingly if the header row is added after the initial paint, the resize handle is visible and usable, but on the second header row, instead of where I would assume it to be (on first header row)
```java
@Route("")
public class MainView extends VerticalLayout {

	public MainView() {
		TreeGrid<Object> treeGrid = new TreeGrid<>();

		Column<Object> firstColumn = treeGrid.addColumn(o -> "mock data").setHeader("This is the header")
				.setResizable(true);

		System.out.println("before: " + firstColumn.isResizable());
		treeGrid.addColumn(o -> "more mock data").setHeader("This is the header");
		treeGrid.setSelectionMode(SelectionMode.MULTI);
		treeGrid.addItemClickListener(click -> {

			GridSelectionModel<Object> selection = treeGrid.getSelectionModel();
			if (selection.isSelected(click.getItem())) {
				selection.deselect(click.getItem());
			} else {
				selection.select(click.getItem());
			}
		});
		
//		add(new Button("add header row", click ->
//		{

			HeaderRow headerRow = treeGrid.appendHeaderRow();
			headerRow.getCell(firstColumn).setComponent(new TextField());

			System.out.println("after: " + firstColumn.isResizable());
//		}
//		));


		treeGrid.setItems(new Object(), new Object());

		System.out.println("cols: " + treeGrid.getColumns());
		add(treeGrid);
	}
}
```

If you modify the above example to only add the header row on button click, the resize handles are visible and usable but IMO on the wrong header row.

**Comment by eriklumme** [comment]
Same happens when appending two footer rows.

**Comment by pekam** [comment]
> Interestingly if the header row is added after the initial paint, the resize handle is visible and usable, but on the second header row, instead of where I would assume it to be (on first header row)

One clarification: `setResizable` is API of `Column`, not any header or header row. When you make a column resizable, I'd consider it as expected behavior to have resize-handles on the bottom-most header.

**Comment by Haprog** [comment]
`appendHeaderRow()` seems to wrap every existing root level `<vaadin-grid-column>` in a new `<vaadin-grid-column-group>` and move's the old column's header to the new column group and sets the "new row" contents to the old column element to get the order right so that we get a new header row at the bottom.

Seems like this Java API is a bit weird abstraction since it's basically abusing the client side column group feature for creating additional header rows (without actually grouping anything). We don't even have any examples doing this kind of additional header/footer rows (without grouping) with the client side component since there it doesn't really seem to have a feature designed for this.

In the above example if not running `appendHeaderRow()` the result will be so that the grid has two `<vaadin-grid-column>` elements with header "This is the header". But if you run the `appendHeaderRow()` part and the text field, then the first column (after the selection column) will be a `<vaadin-grid-column-group>` (with header "This is the header") that contains a `<vaadin-grid-column>` (with the `<vaadin-text-field>` in the header). Then the `firstColumn` object actually still refers to the original `<vaadin-grid-column>` element. It kind of makes sense but after this operation if you would e.g. `firstColumn.setResizable(true)` it probably doesn't do what you expect since it would try to set the `resizable = true` property only on the `<vaadin-grid-column>` but not on the `<vaadin-grid-column-group>`.

However there at least seems to be a minor bug in the `vaadin-grid-column-group` component since it seems to always override the `resizable` properties of the columns it contains whenever the contained columns change or whenever `resizable` is changed on the group.

In this case the `vaadin-grid-column-group` has `resizable == undefined` so when the original column is moved into the group its `resizable` is also set to `undefined` (which doesn't trigger change event to remove the resize handle if it is already created). I will commit a fix for this so that in this case it doesn't override `resizable` on children if the group has it as `undefined` so then with this example I think the resize handle should show and work even if header row is added immediately, but it would still show it only only the second header row (unless the flow component is changed to also set it on the group).

Here's a workaround for setting `resizable = true` on the `vaadin-grid-column-group` after adding header rows to make the whole column properly resizable (you would see the resize handle on all header cells of the column):

```java
treeGrid.getColumnLayers().get(1).getColumns().get(0).setResizable(true);
```

We probably need to open a related issue on `vaadin-grid-flow` so that it would manage setting the `resizable` property on the created column group when adding a new header row (there also might be similar issues with other properties).

**Comment by pekam** [comment]
This seems to be a duplicate or at least related to https://github.com/vaadin/vaadin-grid-flow/issues/234

@Haprog, your workaround probably fails outside of `grid`-package as `getColumnLayers` is protected API (unless you extend `Grid` and use it in subclass).

**Comment by Haprog** [comment]
@pekam Oh right, I was only testing the method call from IntelliJ IDEA debugger when at a breakpoint and there it didn't complain about running it. Didn't notice that API was protected.

Here's a working workaround to get the resize handle on both header rows of the column:
```java
firstColumn.getElement().getParent().callFunction("setAttribute", "resizable", true);
```

Or to get it only on the bottom row:
```java
firstColumn.getElement().callFunction("setAttribute", "resizable", true);
```

This needs to be run after all calls to `appendHeaderRow()`, `prependHeaderRow()`, `appendFooterRow()` and `prependFooterRow()`.

And yes vaadin/vaadin-grid-flow#234 seems like a duplicate.

**Comment by Haprog** [comment]
If you want the resize handle only on the top row, then this seems to work:
```java
firstColumn.getElement().executeJavaScript("this.parentElement.resizable = true; this.resizable = false;");
```

**Comment by Haprog** [comment]
This fix has been released in `vaadin-grid` [v5.4.4](https://github.com/vaadin/vaadin-grid/releases/tag/v5.4.4)

**Comment by Haprog** [comment]
The Java example from the issue description now works (resize handle is usable) if you use the latest version:
```xml
<dependency>
    <groupId>org.webjars.bowergithub.vaadin</groupId>
    <artifactId>vaadin-grid</artifactId>
    <version>5.4.4</version>
</dependency>
```

Though in this case the resize handle only appears on the second header row due to the way the Grid Java API works (regarding adding header/footer rows and setting resizability). If you want a change in this behaviour, please open a new issue in the `vaadin-grid-flow` repo here https://github.com/vaadin/vaadin-grid-flow/issues describing how you think it should work.

**Comment by netsrotr** [comment]
How about this issue now? It is 5 years old and still does not work "out-of-the-box" by setting `column.setResizable(true)`.
With additional header rows the resize handle is only shown at the very bottom additional header row, not at the top heaader row. No API to control where to show the resize handle. I would at least expect the see the resize handle in the first header row, not somewhere else.
